// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        // google()
        mavenCentral()
        //gradlePluginPortal()
    }
    dependencies {
        // Some dependencies are registered here so that they are resolved
        // before the AGP activates, as AGP has transitive dependencies
        // to versions of these libraries reported as vulnerable by GitHub
        // dependabot.
        classpath 'org.jdom:jdom2:2.0.6.1'
        classpath 'io.netty:netty-codec-http:4.1.132.Final'
        classpath 'io.netty:netty-codec-http2:4.1.132.Final'
        classpath 'org.bitbucket.b_c:jose4j:0.9.6'
        classpath 'org.codehaus.plexus:plexus-utils:4.0.3'
        classpath 'org.bouncycastle:bcprov-jdk18on:1.84'
        classpath 'org.apache.commons:commons-lang3:3.20.0'
        classpath 'org.apache.commons:commons-collections4:4.5.0'
        classpath 'commons-io:commons-io:2.22.0'

    }
}

plugins {
    // No global plugins
}

// Version numbering mainly relates to the android-app subproject
// but is managed here to keep it consistent across the other
// subprojects

// Google Play store requires versionCode for releases to be
// monotonically increasing
// as I had already used versionCode 235097892 before I found
// this out, the pattern is now
// prefix 3
// 2 digits each for for major, minor, patch version number
// 2 trailing digit starts at zero can be updated for successive
// build attempts within the same release number
ext.versionCode=300030001

ext.versionName="0.3.0"


